name: Deploy to Live Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup .env and Generate App Key
        run: |
          cp .env.example .env
          php artisan key:generate --force

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Node.js dependencies
        run: |
          bun install
          bun run build

      - name: Deploy via Rsync over SSH
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --exclude='.env' --exclude='.htaccess' --exclude='node_modules'
          path: "./" # Local directory to deploy
          remote_path: ${{ secrets.SSH_PATH }}/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}

      - name: Run Remote SSH Commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_PATH }}
            php artisan migrate --force
            php artisan optimize:clear
